<program> ::= <statement> | <statement> <NEWLINE> <program>
<statement> ::= <field_decl> | <pattern_decl> | <seq_decl> | <comment>
<comment> ::= "#" ( [1-9] | [a-z] )+

<field_decl> ::= "field" <WHITESPACE> <ident> ":" <WHITESPACE>* <field_gen_ident>
<pattern_decl> ::= "pattern" <WHITESPACE> <ident> ":" <WHITESPACE>* <pattern_body>
<seq_decl> ::= "sequence" <WHITESPACE> <ident> ":" <WHITESPACE>* <NEWLINE>? <seq_body>

<src_gen_field> ::= <src_field> | "Any[" <WHITESPACE>* <src_field_list> <WHITESPACE>* "]"
<src_field_list> ::= <src_field> | <src_field> <SEPARATOR> <src_field_list>
<src_field> ::= <src_ident> "(" ( ("\"" <src_name> "\"") | <src_id>) ")"
<src_name> ::= <LETTER> ( <LETTER> | <DIGIT> | "_" )*
<src_id> ::= [0-9]+ | <src_id_hex>
<src_id_hex> ::= "0x" <HEX_DIGIT> <HEX_DIGIT> <HEX_DIGIT> <HEX_DIGIT>
<src_ident> ::= "Mat" | "Surf" | "MatSurf" | "Light" | "Detector"

<pattern_body> ::= "|" <WHITESPACE>* <pipeline_id> <CONCAT> <pattern_event> <CONCAT> <src_field> <WHITESPACE>* "|"
<pipeline_id> ::= "MCRT" | "Emission" | "Detection"
<pattern_event> ::= <pattern_token> | <pattern_token> <CONCAT> <pattern_event>
<pattern_token> ::= <field_gen_ident> | "*" | <ident>

<field_gen_ident> ::= <field_ident> | "Any[" <WHITESPACE>* <field_ident_list> <WHITESPACE>* "]"
<field_ident_list> ::= <field_ident> | <field_ident> <SEPARATOR> <field_ident_list>
<field_ident> ::= "Material" | "Interface" | "Reflector" | "Refraction" | "Reflection" | "Elastic" | "Inelastic" | <field_refl_ident> | <field_scat_ident> | <field_dir_ident>
<field_dir_ident> ::= "Dir::Forward" | "Dir::Backward" | "Dir::Side" | "Dir::Any"
<field_refl_ident> ::= "Diffuse" | "Specular" | "Composite"
<field_scat_ident> ::= "Mie" | "Rayleigh" | "Henyey-Greenstein"

<seq_body> ::= <SEQ_TYPE> (<pattern_body> | <ident>) | <SEQ_TYPE> (<pattern_body> | <ident>) <NEWLINE> <seq_body>


<SEQ_TYPE> ::= E | "!" | ([1-9] [0-9]*) | "N"
<ident> ::= <LETTER> ( <LETTER> | <DIGIT> | "_" )*
<LETTER> ::= [a-z] | [A-Z]
<DIGIT> ::= [0-9]
<WHITESPACE> ::= " "
<NEWLINE> ::= "\n" | "\r\n"
<HEX_DIGIT> ::= [0-9] | [a-f] | [A-F]
<CONCAT> ::= <WHITESPACE>* "|" <WHITESPACE>*
<SEPARATOR> ::= <WHITESPACE>* "," <WHITESPACE>*
