[book]
title = "Eldritch-Trace Documentation"
description = "User Guide and Language Reference Manual for .et DSL"
authors = ["Cristian Bourceanu"]
language = "en"
src = "src"

[build]
build-dir = "build"

[output.html]
additional-js = [
  "theme/et-highlight.js"
]
git-repository-url = "https://github.com/aetherus-wg/eldritch-trace"
